const FETCH_STOCKS_REQUEST = 'FETCH_STOCKS_REQUEST';
const FETCH_STOCKS_SUCCESS = 'FETCH_STOCKS_SUCCESS';
const FETCH_STOCKS_FAILURE = 'FETCH_STOCKS_FAILURE';

export { FETCH_STOCKS_REQUEST, FETCH_STOCKS_SUCCESS, FETCH_STOCKS_FAILURE };
